name: Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run weekly security scan
    - cron: '0 0 * * 0'

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install safety bandit semgrep
    
    - name: Run Safety (Python dependency check)
      run: safety check --json --output safety-report.json || true
    
    - name: Run Bandit (Python security linting)
      run: bandit -r services/ shared/ -f json -o bandit-report.json || true
    
    - name: Run Semgrep (Multi-language security scan)
      run: |
        python -m semgrep --config=auto services/ shared/ --json --output=semgrep-report.json || true
    
    - name: Upload Security Reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: security-reports
        path: |
          safety-report.json
          bandit-report.json
          semgrep-report.json

  dependency-review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v4
    - name: 'Dependency Review'
      uses: actions/dependency-review-action@v3
      with:
        fail-on-severity: moderate
